camera model: Manta G-234B NIR
camera id: DEV_000F314E1E59 # Necessary to select the camera
pixel size: 5.86 # Given in micron
pxls height: 1216 # Number of pixels in vertical
pxls width: 1936 # Number of pixels in horizontal
data folder: '../Data/'
file name: 'frog_meas'
file type: '.tiff'
center wavelength: 345 # in nm, center wavelength of the pulse
focal length: 200 # in mm, lens between grating and camera
grating: 0.81 # Grating specified with 0.81nm/mrad